import Head from 'next/head'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>direct-div</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/logo.png" />
      </Head>

      <Sidebar />
    </div>
  )
}
